### ISSUE TITLE
How to get component data object..?

### ISSUE THREAD

**Issue by kdevkr** [PygmySlowLoris/vue-stepper#11]
I want to get the component's data when the 'vue-stepper' stepper-finised event is called.

**Comment by kentuport** [comment]
In your case:
1. Update your root .vue component - add new array in data (after Steps). 
myData: {
 step1: null,
step2: null
}
And add in <horizontal-stepper :myData="myData"></horizontal-stepper>
2. Then you need to update node_modules/vue-stepper/src/HorizontalStepper.vue - add myData in props.
3. Update your steps components - add myData in props
And in each component add watch like this:
'form.username': function (val, oldval) {
                this.myData.step1 = val
            }

Sorry my english, i hope this will be useful =)

**Comment by kdevkr** [comment]
Thank's for your answer.
but,
I think I don't like update your HorizontalStepper... :(
so, i'm touched $children using ref(horizontal-stepper) 
i don't like either...

**Comment by warrior7789** [comment]
got error  Error in callback for watcher "form.username": "TypeError: Cannot set property 'step1' of undefined"
