### ISSUE TITLE
How do I pass properties to my imported component.

### ISSUE THREAD

**Issue by shealavington** [PygmySlowLoris/vue-stepper#17]
I pass a "component" to HorizontalStepper through the Steps prop, however, the component I'd like to render in the content requires a property itsself, how can I give my component a property?

`
{
    title: 'Image one',
    component: ImageEditor,
    completed: false
}
`

**Comment by alfredrumss** [comment]
@shealavington how did you solve this?

**Comment by CrazyCrud** [comment]
Anybody solved this issue?

**Comment by kashid16** [comment]
Is there any solution to this?
