### ISSUE TITLE
How can I listen to an event on step content (child) component?

### ISSUE THREAD

**Issue by metalcamp** [PygmySlowLoris/vue-stepper#23]
Main component (stepper) listens to beforeNextStep event. Can I somehow pass this event / listen to it on child component? I would like to post data that has been entered on current step to api before I continue to next step.

**Comment by Tiorzfk** [comment]
@metalcamp how did you solve this?

**Comment by joshharington** [comment]
Has anyone solved this? @Tiorzfk @metalcamp

**Comment by kashid16** [comment]
Is there any solution to this? @Tiorzfk @metalcamp
