### ISSUE TITLE
Setting current step

### ISSUE THREAD

**Issue by pkraus109** [PygmySlowLoris/vue-stepper#5]
I have saving the data collected from each step to vuex and also local storage. The idea being if they get interrupted for any reason and come back i can read local storage into vuex for the stepper and then take them to the step they are on.

I can't figure out how to set the current step.

**Comment by hazzo** [comment]
Hi pkraus109, there is actually no prop to set an active step. But you could ref the component and trigger one of his methods, `activateStep (indexStep)` will do it.
Tell me if this works for you.
Thanks!

**Comment by pkraus109** [comment]
Exactly what i needed. Thanks!

**Comment by hazzo** [comment]
Glad we could help you. I'll take this issue as resolved.
