### ISSUE TITLE
Form won't get automatically validated if clicked multiple times back and next

### ISSUE THREAD

**Issue by sheriffmarley** [PygmySlowLoris/vue-stepper#7]
Hello,

I'm using your setpper in one of my projects. And I have a problem when you switch multiple times between two steps.
Each step has a form which gets validated with vuelidate.

1.) You fill out the form, Next button gets clickable -> click it.
2.) You fill out form two. Next button gets clickable. You think you have an error in form 1 and you go back
3) You see that there wasn't any error, you click next. Now the Next button in step 2 has been disabled. 

I logged the handler to console and its only called if you click next the first time on step 1 and only once if you click back on step 2, even if you click multiple times back and next.

Am I doing sth wrong, is it a bug, or am I misunderstanding sth with vue? 

How can I get rid of this behaviour?

**Comment by hazzo** [comment]
Hi @sheriffmarley. Please check that on step two when you come back again and the form is complete the Boolean that triggers the next button to be enabled is set to true. It could be that vualidate is not executing any validation if the form is not touched.

**Comment by hazzo** [comment]
You should implement vualidate API on component render. The stepper should not be responsible for this action.

**Comment by sheriffmarley** [comment]
Like 
```js
        render(){
            console.log("Render description");
            this.$v.form.$touch();
        }
```
?
If so, it's never called.

Never used render before. Sorry for that

**Comment by hazzo** [comment]
When I mean render is the mounted() method in your step component that will be triggered each time a step changes. Tell me if this helps you.

**Comment by sheriffmarley** [comment]
Doesn't help. Have `this.$v.form.touch` on every step in the `mounted()` method.

It's like I click next, It works. I click back, it works. I click next again, i get to the next step but the next button is disabled. If I click back again, the next button of step one is also disabled now. I also don't get any output of the created() or mounted() method anymore

**Comment by hazzo** [comment]
You are using the keep alive prop try using the activated and deactivated life cycles.

**Comment by ianarsenault** [comment]
Nevermind I was able to resolve this issue by adding 

``` js
beforeMount() {
    this.$emit('can-continue', {value: true});
},
```

**Comment by sleroy** [comment]
I had the same issue. 

You may use either a shared event bus between the steps and the parent , passed as a props. And modify the parent to trigger an event to launch the refresh in the step component.
